name: Test Report
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
    inputs:
      marker:
        description: "Marker name"
        required: false

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Dependencies
        run: |
          pipenv install --deploy --dev

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install Firefox
        uses: browser-actions/setup-geckodriver@latest

      - name: Test 
        run: |
          if [[ -n "${{ inputs.marker }}" ]]; then
            pipenv run pytest -m ${{ inputs.marker }}  --alluredir=allure-results
            echo "Running tests with marker: ${{ inputs.marker }}"
          else 
            pipenv run pytest --alluredir=allure-results
          fi
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Deploy Report
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: allure-history
