# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 🚀 Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
    inputs:
      test_file:
        description: "The name of the test file"
        required: false
        
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.x"
    - name: Install pipenv
      run: |
          python -m pip install --upgrade pipenv wheel
          
    - id: cache-pipenv
      uses: actions/cache@v1
      with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --deploy --dev
  
  Linting:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
  Test:
    needs: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Test with pytest - ( Marker ${{ inputs.marker }} )
      run: |
        if [ -z "${{ inputs.marker }}" ]; then
          pipenv run pytest -m ${{ inputs.marker }}
          echo "Running tests with marker: ${{ inputs.marker }}"
        else 
          pipenv run pytest --alluredir=allure-results
        fi
  
  Report:
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
          allure_results: allure-results
          allure_history: allure-history

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: allure-history
